name: movies_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.4.0
environment:
  sdk: ^3.10.7
dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  # A powerful HTTP networking package.
  dio: ^5.9.0
  # Flutter plugin to save images/videos to photos gallery.
  gal: ^2.3.2
  # Contains code to deal with internationalized/localized messages, date and number formatting.
  intl: ^0.20.2
  # RxDart is an implementation of the popular ReactiveX api for asynchronous programming.
  rxdart: ^0.28.0
  # Explicitly reads environment variables into a dart file from a .env file.
  envied: ^1.3.2
  # Simple direct Service Locator that allows to decouple the interface from a concrete implementation.
  get_it: ^9.2.0
  # Lightweight and blazing fast key-value database written in pure Dart.
  hive_ce: ^2.19.0
  # Retrofit.dart is an dio client generator.
  retrofit: ^4.9.2
  # A declarative router for Flutter based on Navigation 2.
  go_router: ^17.0.1
  # Injectable is a convenient code generator for get_it.
  injectable: ^2.7.1+4
  # A Flutter plugin that helps you to restart the whole Flutter app.
  restart_app: ^1.3.2
  # The Flutter code generator for your assets, fonts, colors.
  flutter_gen: ^5.12.0
  # An SVG rendering and widget library for Flutter.
  flutter_svg: ^2.2.3
  # Converts already built widgets into skeleton loaders with no extra effort.
  skeletonizer: ^2.1.2
  # Flutter Widgets that make it easy to implement the BLoC.
  flutter_bloc: ^9.1.1
  # An extension to the bloc state management library which automatically persists and restores bloc states.
  hydrated_bloc: ^10.1.1
  # Flutter plugin for getting commonly used locations on host platform file systems.
  path_provider: ^2.1.5
  # Extension for Hive. Makes it easier to use Hive in Flutter apps.
  hive_ce_flutter: ^2.3.4
  # Classes and helper functions that support JSON code generation.
  json_annotation: ^4.9.0
  # A Flutter plugin that provides a WebView widget.
  webview_flutter: ^4.13.1
  # A carousel slider widget.
  carousel_slider: ^5.1.1
  # Default icons asset for Cupertino widgets.
  cupertino_icons: ^1.0.8
  # A simple yet fully customizable ratingbar for flutter.
  flutter_rating_bar: ^4.0.1
  # Flutter plugin for reading and writing simple key-value pairs.
  shared_preferences: ^2.5.4
  # Flutter library to load and cache network images.
  cached_network_image: ^3.4.1
  # Flutter Secure Storage provides API to store data in secure storage.
  flutter_secure_storage: ^10.0.0
  # Flutter plugin for playing or streaming inline YouTube videos.
  youtube_player_flutter: ^9.1.3
  # A pure Dart library that checks for internet.
  internet_connection_checker: ^3.0.1
dev_dependencies:
  # Set of lint rules for the Flutter BLoC library.
  bloc_lint: ^0.3.6
  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.10.5
  # Recommended lints for Flutter apps.
  flutter_lints: ^6.0.0
  # Generator for the Envied package.
  envied_generator: ^1.3.2
  # A builder that supports generated strongly-typed route helpers for package:go_router.
  go_router_builder: ^4.1.3
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.11.4
  # Extension for Hive. Automatically generates TypeAdapters to store any class.
  hive_ce_generator: ^1.9.3
  # retrofit generator is an dio client generator
  retrofit_generator: ^10.2.1
  # The Flutter code generator for your assets, fonts, colors.
  flutter_gen_runner: ^5.12.0
  # Injectable_generator is a convenient code generator for Injectable.
  injectable_generator: ^2.12.0
  # Customize Flutter's default native splash screen.
  flutter_native_splash: ^2.4.7
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/splash/
  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
    - family: cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/cairo/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/cairo/Cairo-Black.ttf
          weight: 900

flutter_gen:
  output: lib/core/gen/
  line_length: 80
  assets:
    enabled: false
  fonts:
    enabled: false
  colors:
    enabled: false